[profile.default]
bytecode_hash = "none"
fuzz = { runs = 1_000 }
gas_reports = ["*"]
optimizer = true
optimizer_runs = 16
out = "out"
script = "script"
solc = "0.8.24"
src = "src"
test = "test"
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
